### ISSUE TITLE
Gibwork Bounty - MPL-404

### ISSUE THREAD

**Issue by enzotar** [space-operator/flow-backend#152]
No program to write, simply passing correct accounts & data to invoke the MPL-404 instructions and making visual flows.

Reference X post
https://x.com/blinks_gg/status/1852074278910398472

Bounty link
https://app.gib.work/bounties/aeb1c1a9-9af0-4265-9501-8c9e469afd0b

**Comment by Adil7755** [comment]
Best wrok

**Comment by Heiirap** [comment]
good work

**Comment by Julibal** [comment]
Have configured the necessary thing and it has been fixed.
